name: alaska
description: A sample dart example showing how to read data from postgis

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  dart_jts: any
  postgres:
    path: ../postgresql-dart
    # git:
    #   url: https://github.com/bettdouglas/postgresql-dart.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
